server:
  port: 8118

spring:
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://192.168.233.129:3306/blog?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  mvc:
    favicon:
      enbaled: false

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true

mybatis:
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    root: info
    com.traning.blog: debug


